pre-commit: Apply uncrustify and KWStyle check for modified files.
uncrustify (uncrustify.sourceforge.net) is applied to changed files prior to
commit.

This feature is off by default.  To enable this behavior, set

  git config hooks.uncrustify true

By default, the behavior of git-mergetool is used to review the changes
uncrustify makes before they are added to the commit.  For more information on
this behavior, see

  git help mergetool

To disable review with mergetool

  git config hooks.uncrustify.mergetool false

All changes suggested by uncrustify will automatically be added to the
commit (dangerous).

TODO: Figure out how a terminal reset can be prevented when using vimdiff.

KWStyle is run on the changed files and the commit is aborted if the files do
not pass the test.  A file similar to the original is saved with a '*.kws'
extension so that line numbers referenced in the error message can be examined.

The test is on by default.  To avoid running the KWStyle tests

  git config hooks.KWStyle false

Project specific uncrustify and KWStyle configuration files are set with 'git
config'.  For example

  git config hooks.uncrustify.conf /path/to/uncrustify.conf
  git config hooks.KWStyle.conf /path/to/KWStyle.conf
  git config hooks.KWStyle.overwriteRulesConf /path/to/overwrite.conf # optional

If the appropriate values have not been set, die() is called.  An
optional KWStyle overwrite rules file can also been configured.

In ITK, this is intended to be used with the Utilities/hooks.sh script to set up the
appropriate values.

Change-Id: Ia6b2d4136af3002eb0ec5d36f03c50df928917f4

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -239,3 +239,163 @@ while read src_mode dst_mode src_obj dst_obj status file; do
 done
 )
 test -z "$bad" || die "$bad"
+
+check_for_KWStyle() {
+  if ! which KWStyle &> /dev/null; then
+    die "KWStyle was not found in the system PATH.
+  Please install KWStyle.
+  See http://public.kitware.com/KWStyle/"
+  fi
+
+  KWStyle_conf=$(git config hooks.KWStyle.conf)
+  if ! test -f "$KWStyle_conf"; then
+    die "The file '$KWStyle_conf' does not exist.
+
+Please run
+
+  git config hooks.KWStyle.conf /path/to/KWStyle.conf.xml"
+  fi
+  KWStyle_overWriteRulesConf=$(git config hooks.KWStyle.overwriteRulesConf || "")
+  if test -z "$KWStyle_overWriteRulesConf" && \
+    test -f "$KWStyle_overWriteRulesConf"; then
+    die "The hooks.KWStyle.overwriteRulesConf file '$KWStyle_overWriteRulesConf' does not exist."
+  fi
+
+}
+
+run_KWStyle_on_file() {
+  if test -z "$KWStyle_overWriteRulesConf"; then
+    KWStyle -v -xml "$KWStyle_conf" "$1"
+  else
+    KWStyle -v -xml "$KWStyle_conf" -o "$KWStyle_overWriteRulesConf" "$1"
+  fi
+
+  if test $? -ne 0; then
+    cp -- "$1"{,.kws}
+    die "KWStyle check failed.
+
+Line numbers in the errors shown refer to the file:
+${1}.kws"
+  fi
+}
+
+run_KWStyle() {
+  for f in $(git diff-index --cached --diff-filter=ACMR --name-only $against --); do
+    if expr match "$f" "$cxx_src_files_expr"; then
+      run_KWStyle_on_file "$f"
+    fi
+  done
+}
+
+do_KWStyle=$(git config --bool hooks.KWStyle || echo true)
+
+check_for_uncrustify() {
+  if ! which uncrustify &> /dev/null; then
+    die "uncrustify was not found in the system PATH.
+  Please install uncrustify.
+  See http://uncrustify.sourceforge.net/"
+  fi
+
+  uncrustify_conf=$(git config hooks.uncrustify.conf)
+  if ! test -f "$uncrustify_conf"; then
+    die "The file '$uncrustify_conf' does not exist.
+
+Please run
+
+  git config hooks.uncrustify.conf /path/to/uncrustify.conf"
+  fi
+}
+
+# We use git-mergetool settings to review the uncrustify changes
+TOOL_MODE=merge
+source "$(git --exec-path)/git-mergetool--lib"
+# Redefine check_unchanged because we do not need to check if the merge was
+# successful.
+check_unchanged() {
+  status=0
+}
+
+cxx_src_files_expr='.*\.\(h\|h\.in|cpp\|cpp\.in\|cxx\|cxx\.in\|txx\|txx\.in\)$'
+
+run_uncrustify() {
+  $do_KWStyle && check_for_KWStyle
+
+  uncrustify_use_merge_tool=$(git config --bool hooks.uncrustify.mergetool || \
+  echo true)
+  merge_tool=$(get_merge_tool "$merge_tool") || exit
+  merge_keep_backup="$(git config --bool mergetool.keepBackup || echo true)"
+  merge_keep_temporaries="$(git config --bool mergetool.keepTemporaries || echo false)"
+  for MERGED in $(git diff-index --cached --diff-filter=ACMR --name-only $against -- )
+  do
+    if expr match "$MERGED" "$cxx_src_files_expr"; then
+      ext="$$$(expr "$MERGED" : '.*\(\.[^/]*\)$')"
+      BACKUP="./$MERGED.BACKUP.$ext"
+      LOCAL="./$MERGED.LOCAL.$ext"
+      REMOTE="./$MERGED.REMOTE.$ext"
+      NEW_MERGED="./$MERGED.NEW.$ext"
+      OLD_MERGED="$MERGED"
+
+      mv -- "$MERGED" "$BACKUP"
+      # We temporarily change MERGED because the file might already be open, and
+      # the editor may complain.
+      MERGED="$NEW_MERGED"
+      cp -- "$BACKUP" "$MERGED"
+      cp -- "$BACKUP" "$LOCAL"
+
+      if ! uncrustify -c "$uncrustify_conf" -l CPP -f "$LOCAL" \
+        -o "$REMOTE" 2> /dev/null; then
+          mv -- "$BACKUP" "$OLD_MERGED"
+
+          if test "$merge_keep_temporaries" = "false"; then
+              rm -f -- "$LOCAL" "$REMOTE" "$BACKUP"
+          fi
+
+          die "error when running uncrustify on $OLD_MERGED"
+      fi
+
+      if $uncrustify_use_merge_tool; then
+        if ! run_merge_tool "$merge_tool" "false"; then
+            mv -- "$BACKUP" "$OLD_MERGED"
+
+            if test "$merge_keep_temporaries" = "false"; then
+                rm -f -- "$LOCAL" "$REMOTE" "$BACKUP" "$NEW_MERGED"
+            fi
+
+            die "uncrustify merge of $MERGED failed"
+        fi
+      else
+        cp -- "$REMOTE" "$MERGED"
+      fi
+
+      mv -- "$NEW_MERGED" "$OLD_MERGED"
+      MERGED="$OLD_MERGED"
+
+      if test "$merge_keep_backup" = "true"; then
+          mv -- "$BACKUP" "$MERGED.orig"
+      else
+          rm -- "$BACKUP"
+      fi
+
+      git add -- "$MERGED"
+      rm -f -- "$LOCAL" "$REMOTE" "$BACKUP"
+
+      # The terminal gets fiddled with?
+      reset
+
+      $do_KWStyle && run_KWStyle_on_file "$MERGED"
+    fi # end if CXX file
+  done # end for changed files
+}
+
+do_uncrustify=$(git config --bool hooks.uncrustify || echo false)
+
+if $do_uncrustify; then
+  check_for_uncrustify
+  run_uncrustify
+fi
+
+
+if $do_KWStyle && ! $do_uncrustify; then
+  check_for_KWStyle
+  run_KWStyle
+fi
